services:
  - type: web
    name: twilchat-backend
    runtime: node
    buildCommand: npm run build
    startCommand: node server.js
    dir: backend
    envVars:
      - key: NODE_ENV
        value: production
